# Generated by Django 4.0.1 on 2022-01-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
